version: 0.1
            
phases:

  build:
    commands:

      # Build our application
      - go get github.com/tools/godep
      - godep restore
      - ls ./
      - go build -o api

artifacts:
  files:
    - api